In [53]:
import numpy as np
import pandas as pd

In [17]:
weather_data=['sun', 'rain', 'cloud', 'cloud', 'sun', 'sun', 'cloud', 'rain', 
  'rain', 'cloud', 'rain', 'sun', 'cloud', 'cloud', 'sun', 'sun', 
  'cloud', 'cloud', 'rain', 'rain', 'sun', 'rain', 'cloud', 'sun',
  'sun', 'cloud', 'rain', 'rain', 'cloud', 'sun', 'sun', 'cloud', 
  'rain', 'sun', 'cloud', 'cloud', 'sun', 'sun', 'cloud', 'cloud', 
  'rain', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun', 'cloud', 'cloud', 
  'cloud', 'cloud', 'rain', 'cloud', 'cloud', 'sun', 'sun', 'sun', 
  'cloud', 'sun', 'rain', 'rain', 'sun', 'sun', 'sun', 'rain', 
  'rain', 'cloud', 'cloud', 'sun', 'sun', 'sun', 'sun', 'cloud', 'sun', 
  'cloud', 'cloud', 'cloud', 'rain', 'rain', 'cloud', 'rain', 
  'rain', 'cloud', 'cloud', 'sun', 'cloud', 'rain', 'rain', 'rain', 
  'cloud', 'sun', 'sun', 'sun', 'cloud', 'sun', 'sun', 'cloud', 'cloud',
  'sun', 'sun']

In [33]:
ar = np.array(weather_data, dtype='|S1').view(np.uint8)

## Getting Initial probability

In [20]:
print(weather_data.count('sun')/len(weather_data))
print(weather_data.count('rain')/len(weather_data))
print(weather_data.count('cloud')/len(weather_data))

0.38
0.25
0.37


### q = (0.38,0.25,0.37)

In [34]:
c, r, s = 99, 114, 115 # you can verify this using chr and ord
lookup = np.empty((s+1,), dtype=int)
lookup[[c, r, s]] = np.arange(3)

In [48]:
# translate c, r, s to 0, 1, 2
rc = lookup[ar]

In [57]:
# get counts (of pairs (today, tomorrow))
count = np.zeros((3, 3), dtype=int)
np.add.at(count, (rc[:-1], rc[1:]), 1)
print(count)

[[14 10 13]
 [ 9 11  5]
 [14  4 19]]


In [58]:
# or as probs
probs = count / count.sum()
print(probs)

[[0.14141414 0.1010101  0.13131313]
 [0.09090909 0.11111111 0.05050505]
 [0.14141414 0.04040404 0.19191919]]


### Future values

In [59]:
# if today is sun how probable is rain tomorrow etc.
cond = count / count.sum(axis=-1, keepdims=True)
print(cond)

[[0.37837838 0.27027027 0.35135135]
 [0.36       0.44       0.2       ]
 [0.37837838 0.10810811 0.51351351]]


#### CHECKING USING PANDAS DATAFRAME

In [56]:
df = pd.DataFrame(columns = ['state', 'next_state'])
for i, val in enumerate(weather_data[:-1]): # We don't care about last state
    df_stg = pd.DataFrame(index=[0])
    df_stg['state'], df_stg['next_state'] = weather_data[i], weather_data[i+1]
    df = pd.concat([df, df_stg], axis = 0)
cross_tab = pd.crosstab(df['state'], df['next_state'])
cross_tab.div(cross_tab.sum(axis=1), axis=0)

next_state     cloud      rain       sun
state                                   
cloud       0.378378  0.270270  0.351351
rain        0.360000  0.440000  0.200000
sun         0.378378  0.108108  0.513514


### By - 
### ABHISHEK KUMAR
### (20BAI10384)